### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [AlexChemerys/KottansT#2]
Pass `"50000000000006114"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number is invalid)
Actual result: "Maestro"

**Comment by AlexChemerys** [comment]
I bellive this is not an issue. 
wiki says that maestro lenth is 12-19 chars lenght.
also from  "Maestro Global Rules" (PDF). MasterCard. 9 November 2012. 
"The PAN must be no less than twelve (12) and no more than nineteen (19)
digits in length. All digits of the PAN must be numeric."

So i belive that 5000 0000 0000 0611 4 - 17 digits is ok. aslo start of the number is valid for "Maestro",
Please give more feedback on this issue.

**Comment by AlexChemerys** [comment]
forced program to work with 16 digit maestro

**Comment by AlexChemerys** [comment]
issue in luhn, fixed
