### ISSUE TITLE
GenerateNextCreditCardNumber does not work as expected

### ISSUE THREAD

**Issue by intrueder** [AlexChemerys/KottansT#3]
Pass `343434343434343` to `GenerateNextCreditCardNumber` method
Expected result: `343434343434350`
Actual result: `343434343434359`

**Comment by AlexChemerys** [comment]
Issue caused by issue #1 
fixed

**Comment by intrueder** [comment]
Now it returns `340000000000009` for the `343434343434343`
I still expect `343434343434350` as result.

**Comment by AlexChemerys** [comment]
thx for feedback, fixed
